language: python
python:
  - 3.4
# matrix:
#   include:
#     - python: 3.4
#       env:
#         - TEST_MATPLOTLIB="true"
before_install:
  - sudo apt-get update
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - sudo apt-get install -qq python3-sphinx cython3
  # TODO use conda instead
  - pip install "numpy==1.9.1"
  - pip install --allow-external "matplotlib==1.4.0"
  - pip install "mako"
  - mkdir build
  - cd build
  - cmake ..
  - make
notifications:
  email: false
